In [1]:
import numpy as np
import pandas as pd

In [60]:
# 1. Import numpy as np and see the version
print(np.__version__)

1.14.2


In [61]:
# 2. How to create a 1D array?
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#3. How to create a boolean array?

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [63]:
# 4. How to extract items that satisfy a given condition from 1D array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [65]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [66]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(10)
new_arr = np.where(arr % 2 == 1, -1, arr)

In [67]:
# 7. How to reshape an array?
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
# 8. How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
# 9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [73]:
# 10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
np.concatenate([np.repeat(a, 3), np.tile(a, 3)], axis=0)


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [75]:
# 11. How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [77]:
# 13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [78]:
# 14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[np.where((a >= 5) & (a <= 10))]

array([ 6,  9, 10])

In [80]:
# 15. How to make a python function that handles scalars to work on numpy arrays?

def pair_max(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [82]:
# 16. How to swap two columns in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
arr[:, [0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [83]:
# 17. How to swap two rows in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
arr[[0,2,1], :]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [85]:
# 18. How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [86]:
# 19. How to reverse the columns of a 2D array?
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [87]:
# 20. How to create a 2D array containing random floats between 5 and 10?
np.random.uniform(5,10, size=(5,3))

array([[6.71516394, 8.42861961, 6.48820189],
       [5.12325082, 7.89096079, 6.9853485 ],
       [5.36093066, 8.75166644, 5.83446997],
       [9.02113384, 7.47591719, 7.41049195],
       [8.59424578, 5.48302839, 7.09322298]])