# Data Manipulation



To start, we import the PyTorch library.
Note that the package name is `torch`

In [4]:
import torch

A tensor represents a (possibly multi-dimensional) array of numerical values

In [5]:
## 创建torch tensor的方法
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [6]:
## tensor的元素的个数
x.numel()

12

We can access a tensor's *shape*

In [7]:
## 向量为单纯的X，Y，如果是2darray就是(X,Y)这样
x.shape

torch.Size([12])

Change the shape of a tensor
without altering its size or values

In [10]:
X = x.reshape(3, 4)
print(X)
## 你看2d的时候，元素个数不变，但是形态改变
print(X.shape, X.numel())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4]) 12


We can construct a tensor with all elements set to zero
or one

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Sample each element randomly (and independently)

In [13]:
torch.randn(3, 4)

tensor([[ 0.2798, -0.6380, -1.1198, -1.1273],
        [ 1.1500,  0.7675, -0.4201,  1.6678],
        [-2.5294, -0.0221, -1.7760,  2.1427]])

Supplying the exact values for each element

In [14]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

`[-1]` selects the last row and `[1:3]`
selects the second and third rows

In [15]:
## 选出来是一个tuple，分别是两个torch tensor
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

We can also write elements of a matrix by specifying indices

In [16]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

To assign multiple elements the same value,
we apply the indexing on the left-hand side 
of the assignment operation

In [17]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [18]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [20]:
## tensor的计算也是element-wise
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

*concatenate* multiple tensors together

In [25]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
## torch.cat 把两个tensor合在一起
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Construct a binary tensor via *logical statements*

In [26]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Summing all the elements in the tensor

In [27]:
print(X.sum())
print(X.sum(dim=0), X.sum(dim=1))

tensor(66.)
tensor([12., 15., 18., 21.]) tensor([ 6., 22., 38.])


Perform elementwise binary operations
by invoking the *broadcasting mechanism*

In [30]:
## 即使形状不同，仍然存在广播机制，a和b都是2d tensor，a+b的广播机制是a的每一行都会加入b的每一行，b的每一列和a的每一列增加。变成了矩阵相加
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a, b)
print(a + b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


Running operations can cause new memory to be
allocated to host results

In [32]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Performing in-place operations  
如果原地操作，要么新建一个container，更新这个container，要么就替换原本的X或者Y的value。
这就跟numpy array 的np.concat会临时增加多倍的内存，如果新建一个numpy的container，然后更新每个部分，这样可以省下大量的memory

In [33]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2334355999616
id(Z): 2334355999616


If the value of `X` is not reused in subsequent computations,
we can also use `X[:] = X + Y` or `X += Y`
to reduce the memory overhead of the operation

In [34]:
before = id(X)
X += Y
id(X) == before

True

Converting to a NumPy tensor (`ndarray`)

In [35]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

Convert a size-1 tensor to a Python scalar

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 练习部分

运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。

In [37]:
X>Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [40]:
## 但是如果shape的size不相同，就不可以广播
a = torch.arange(6).reshape((3, 2))
b = torch.arange(4).reshape((1, 4))
print(a, b)
print(a + b)

tensor([[0, 1],
        [2, 3],
        [4, 5]]) tensor([[0, 1, 2, 3]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

In [47]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(3).reshape((1, 3))
print(a, b)
print(a + b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1, 2]])
tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])
